### ISSUE TITLE
[202007]YAML简单用用就好

### ISSUE THREAD

**Issue by bingoohuang** [bingoohuang/weekly#67]
我为什么开始用YAML呢？

1. 因为想写注释，所以想到了YAML
2. YAML基础语法很简洁
3. K8S大量使用也使得它非常流行（或者反过来说也行，因为YAML很流行，K8S用了它）

下面一个简单的例子来自于[Ansible中文权威指南](https://ansible-tran.readthedocs.io/en/latest/index.html)

```yaml
---
# 一位职工记录
name: Example Developer
job: Developer
skill: Elite
employed: True
foods:
    - Apple
    - Orange
    - Strawberry
    - Mango
languages:
    ruby: Elite
    python: Elite
    dotnet: Lame
```

[![image](https://user-images.githubusercontent.com/1940588/76705349-66385580-671a-11ea-8a44-5763b5a25478.png)
](https://codebeautify.org/yaml-to-json-xml-csv/cb1bdc0a)

因为对JSON很熟悉，所以把YAML转换为JSON，来验证是否符合自己的期望，例如以下实验YAML多行文本的写法：

[![image](https://user-images.githubusercontent.com/1940588/76683211-4da63d80-663d-11ea-9d57-9e453664338d.png)](https://codebeautify.org/yaml-to-json-xml-csv/cbe6ded5)
